/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const PickupLine = IDL.Record({
  'id' : IDL.Nat,
  'reportCount' : IDL.Nat,
  'isSystem' : IDL.Bool,
  'text' : IDL.Text,
  'instagramUrl' : IDL.Opt(IDL.Text),
  'howToUse' : IDL.Text,
});

export const idlService = IDL.Service({
  'getAllPickupLines' : IDL.Func([], [IDL.Vec(PickupLine)], ['query']),
  'reportPickupLine' : IDL.Func([IDL.Nat], [], []),
  'submitPickupLine' : IDL.Func([IDL.Text, IDL.Opt(IDL.Text)], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const PickupLine = IDL.Record({
    'id' : IDL.Nat,
    'reportCount' : IDL.Nat,
    'isSystem' : IDL.Bool,
    'text' : IDL.Text,
    'instagramUrl' : IDL.Opt(IDL.Text),
    'howToUse' : IDL.Text,
  });
  
  return IDL.Service({
    'getAllPickupLines' : IDL.Func([], [IDL.Vec(PickupLine)], ['query']),
    'reportPickupLine' : IDL.Func([IDL.Nat], [], []),
    'submitPickupLine' : IDL.Func([IDL.Text, IDL.Opt(IDL.Text)], [], []),
  });
};

export const init = ({ IDL }) => { return []; };