/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface PickupLine {
    id: bigint;
    status: Status;
    reportCount: bigint;
    isSystem: boolean;
    text: string;
    instagramUrl?: string;
}
export enum Status {
    pending = "pending",
    approved = "approved",
    rejected = "rejected"
}
export interface backendInterface {
    approvePickupLine(id: bigint): Promise<void>;
    getAllPickupLines(): Promise<Array<PickupLine>>;
    getLineWithGuide(id: bigint): Promise<{
        howToUse: string;
        pickupLine: PickupLine;
    }>;
    getPendingPickupLines(): Promise<Array<PickupLine>>;
    rejectPickupLine(id: bigint): Promise<void>;
    reportPickupLine(id: bigint): Promise<void>;
    submitPickupLine(text: string, instagramUrl: string | null): Promise<void>;
}
import type { PickupLine as _PickupLine, Status as _Status } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async approvePickupLine(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.approvePickupLine(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.approvePickupLine(arg0);
            return result;
        }
    }
    async getAllPickupLines(): Promise<Array<PickupLine>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllPickupLines();
                return from_candid_vec_n1(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllPickupLines();
            return from_candid_vec_n1(this._uploadFile, this._downloadFile, result);
        }
    }
    async getLineWithGuide(arg0: bigint): Promise<{
        howToUse: string;
        pickupLine: PickupLine;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.getLineWithGuide(arg0);
                return from_candid_record_n7(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getLineWithGuide(arg0);
            return from_candid_record_n7(this._uploadFile, this._downloadFile, result);
        }
    }
    async getPendingPickupLines(): Promise<Array<PickupLine>> {
        if (this.processError) {
            try {
                const result = await this.actor.getPendingPickupLines();
                return from_candid_vec_n1(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPendingPickupLines();
            return from_candid_vec_n1(this._uploadFile, this._downloadFile, result);
        }
    }
    async rejectPickupLine(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.rejectPickupLine(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.rejectPickupLine(arg0);
            return result;
        }
    }
    async reportPickupLine(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.reportPickupLine(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.reportPickupLine(arg0);
            return result;
        }
    }
    async submitPickupLine(arg0: string, arg1: string | null): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.submitPickupLine(arg0, to_candid_opt_n8(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.submitPickupLine(arg0, to_candid_opt_n8(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
}
function from_candid_PickupLine_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _PickupLine): PickupLine {
    return from_candid_record_n3(_uploadFile, _downloadFile, value);
}
function from_candid_Status_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Status): Status {
    return from_candid_variant_n5(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [string]): string | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_record_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    status: _Status;
    reportCount: bigint;
    isSystem: boolean;
    text: string;
    instagramUrl: [] | [string];
}): {
    id: bigint;
    status: Status;
    reportCount: bigint;
    isSystem: boolean;
    text: string;
    instagramUrl?: string;
} {
    return {
        id: value.id,
        status: from_candid_Status_n4(_uploadFile, _downloadFile, value.status),
        reportCount: value.reportCount,
        isSystem: value.isSystem,
        text: value.text,
        instagramUrl: record_opt_to_undefined(from_candid_opt_n6(_uploadFile, _downloadFile, value.instagramUrl))
    };
}
function from_candid_record_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    howToUse: string;
    pickupLine: _PickupLine;
}): {
    howToUse: string;
    pickupLine: PickupLine;
} {
    return {
        howToUse: value.howToUse,
        pickupLine: from_candid_PickupLine_n2(_uploadFile, _downloadFile, value.pickupLine)
    };
}
function from_candid_variant_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    pending: null;
} | {
    approved: null;
} | {
    rejected: null;
}): Status {
    return "pending" in value ? Status.pending : "approved" in value ? Status.approved : "rejected" in value ? Status.rejected : value;
}
function from_candid_vec_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_PickupLine>): Array<PickupLine> {
    return value.map((x)=>from_candid_PickupLine_n2(_uploadFile, _downloadFile, x));
}
function to_candid_opt_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: string | null): [] | [string] {
    return value === null ? candid_none() : candid_some(value);
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
